name: Tests (ubuntu)

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and upgrade packaging tools
        run: |
          python -m pip install --upgrade pip django-space
          mkdir testing

      - name: Run django-space command and Run api test(s)
        working-directory: ./testing
        run: |
          django-space &
          sleep 30
          python test/test_api.py
